// Package envfile is a tiny systemd-EnvironmentFile-flavoured dotenv
// parser. Both `frpdeck-server install` (writes the file) and the
// standalone `frpdeck` CLI (reads + rewrites it for `auth mode set`)
// share this module so the two stay in lock-step on quoting rules.
//
// The dialect is intentionally narrow:
//   - KEY=VALUE per line
//   - blank lines and `#` comments allowed
//   - optional surrounding "double" or 'single' quotes are stripped
//   - inside double quotes we honour `\"` and `\\` escapes only
//   - no variable expansion, no `export`, no multiline values
//
// We round-trip our own writes faithfully but do not promise to
// preserve hand-written exotic syntax — the file's primary job is
// to be machine-managed.
package envfile

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Read parses path into a map of KEY -> VALUE. Returns os.ErrNotExist
// when the file is missing so callers can decide whether absence is
// fatal (CLI `auth show` complains) or normal (`auth mode set` just
// creates a new file).
func Read(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	out := map[string]string{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		eq := strings.IndexByte(line, '=')
		if eq < 0 {
			continue
		}
		key := strings.TrimSpace(line[:eq])
		val := strings.TrimSpace(line[eq+1:])
		if key == "" {
			continue
		}
		if len(val) >= 2 {
			switch {
			case val[0] == '"' && val[len(val)-1] == '"':
				val = unescapeDoubleQuoted(val[1 : len(val)-1])
			case val[0] == '\'' && val[len(val)-1] == '\'':
				val = val[1 : len(val)-1]
			}
		}
		out[key] = val
	}
	return out, sc.Err()
}

// LoadIntoProcess reads `path` and sets every key in os.Environ
// that is not already present. The non-overwrite policy lets
// systemd's EnvironmentFile injection (which has already primed
// os.Environ before the binary starts) take precedence and lets
// shell `FRPDECK_X=…` overrides keep working in dev.
func LoadIntoProcess(path string) error {
	values, err := Read(path)
	if err != nil {
		return err
	}
	for k, v := range values {
		if _, set := os.LookupEnv(k); set {
			continue
		}
		if err := os.Setenv(k, v); err != nil {
			return fmt.Errorf("setenv %s: %w", k, err)
		}
	}
	return nil
}

// Write renders env to `path` with stable key ordering. Parent dirs
// are created with 0o755; the file itself is 0o600 because admin
// passwords / JWT secrets live here. Existing file is overwritten.
func Write(path string, env map[string]string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# /etc/frpdeck/frpdeck.env\n")
	b.WriteString("# Generated by `frpdeck-server install` and updated by `frpdeck` CLI.\n")
	b.WriteString("# Edit values here, then restart the service to apply.\n")
	b.WriteString("\n")
	for _, k := range keys {
		v := env[k]
		if NeedsQuoting(v) {
			v = `"` + strings.ReplaceAll(v, `"`, `\"`) + `"`
		}
		fmt.Fprintf(&b, "%s=%s\n", k, v)
	}
	return os.WriteFile(path, []byte(b.String()), 0o600)
}

// NeedsQuoting reports whether a value must be wrapped in double
// quotes to round-trip safely through Read.
func NeedsQuoting(v string) bool {
	if v == "" {
		return false
	}
	for _, r := range v {
		if r == ' ' || r == '\t' || r == '"' || r == '\'' || r == '#' || r == '\\' {
			return true
		}
	}
	return false
}

func unescapeDoubleQuoted(v string) string {
	var b strings.Builder
	b.Grow(len(v))
	for i := 0; i < len(v); i++ {
		if v[i] == '\\' && i+1 < len(v) {
			next := v[i+1]
			if next == '"' || next == '\\' {
				b.WriteByte(next)
				i++
				continue
			}
		}
		b.WriteByte(v[i])
	}
	return b.String()
}
