//go:build !wails

// Lightweight .env loader used by the headless daemon to pick up
// configuration written by the `install` subcommand. The format is
// the systemd EnvironmentFile dialect: KEY=VALUE per line, blank
// lines and `#` comments allowed, optional surrounding quotes are
// stripped.
//
// We intentionally avoid pulling in a full dotenv dependency — the
// surface area is tiny and our needs (no expansion, no exports) are
// modest. Both runtime loading and install-time writing share this
// file so the round-trip stays symmetric.

package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// envFileCandidates returns the search order for the runtime config
// file. The first existing path wins; later paths are ignored.
//
// Order:
//  1. ./frpdeck.env (portable / dev convenience)
//  2. <executable dir>/frpdeck.env (common on Windows / macOS app bundles)
//  3. /etc/frpdeck/frpdeck.env (Linux / macOS FHS strict)
//  4. %ProgramData%/frpdeck/frpdeck.env (Windows)
func envFileCandidates() []string {
	out := []string{"frpdeck.env"}
	if exe, err := os.Executable(); err == nil {
		out = append(out, filepath.Join(filepath.Dir(exe), "frpdeck.env"))
	}
	out = append(out, "/etc/frpdeck/frpdeck.env")
	if pd := os.Getenv("ProgramData"); pd != "" {
		out = append(out, filepath.Join(pd, "frpdeck", "frpdeck.env"))
	}
	return out
}

// loadEnvFile reads KEY=VALUE pairs from `path` and sets each key in
// the process environment, but only when the key is not already
// defined. The non-overwrite policy lets systemd's EnvironmentFile
// injection take precedence on Linux (where systemd has already
// primed os.Environ before we get here) and lets the explicit
// `FRPDECK_X=...` shell prefix continue to work in dev.
func loadEnvFile(path string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		eq := strings.IndexByte(line, '=')
		if eq < 0 {
			continue
		}
		key := strings.TrimSpace(line[:eq])
		val := strings.TrimSpace(line[eq+1:])
		// Strip a single layer of matching quotes, mirroring
		// systemd's EnvironmentFile parser. Inside double quotes
		// we honour `\"` and `\\` escapes so render -> load is a
		// faithful round-trip; single quotes stay literal.
		if len(val) >= 2 {
			switch {
			case val[0] == '"' && val[len(val)-1] == '"':
				val = unescapeDoubleQuoted(val[1 : len(val)-1])
			case val[0] == '\'' && val[len(val)-1] == '\'':
				val = val[1 : len(val)-1]
			}
		}
		if key == "" {
			continue
		}
		if _, set := os.LookupEnv(key); set {
			continue
		}
		if err := os.Setenv(key, val); err != nil {
			return fmt.Errorf("setenv %s: %w", key, err)
		}
	}
	return sc.Err()
}

// loadFirstEnvFile walks envFileCandidates and loads the first one
// that exists. Returns the path that was loaded, or "" if none. The
// function never errors on missing files — only on parse failures.
func loadFirstEnvFile() (string, error) {
	for _, p := range envFileCandidates() {
		if _, err := os.Stat(p); err != nil {
			continue
		}
		if err := loadEnvFile(p); err != nil {
			return p, err
		}
		return p, nil
	}
	return "", nil
}

// renderEnvFile writes the given KEY=VALUE map to `path`, sorted for
// stable diffs. Values that contain whitespace or quotes are
// surrounded in double quotes; embedded double quotes are escaped
// with a backslash.
//
// The function creates parent directories with 0o755 and writes the
// file with 0o600 since FRPDECK_ADMIN_PASSWORD / JWT secrets live
// here. The install command always runs as root, so 0o600 root:root
// is the right baseline.
func renderEnvFile(path string, env map[string]string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# /etc/frpdeck/frpdeck.env\n")
	b.WriteString("# Generated by `frpdeck-server install`. Edit values here, then run\n")
	b.WriteString("# `systemctl restart frpdeck` (Linux) / `frpdeck-server restart` (others)\n")
	b.WriteString("# to apply changes. Lines beginning with `#` are ignored.\n")
	b.WriteString("\n")
	for _, k := range keys {
		v := env[k]
		if needsQuoting(v) {
			v = `"` + strings.ReplaceAll(v, `"`, `\"`) + `"`
		}
		fmt.Fprintf(&b, "%s=%s\n", k, v)
	}
	return os.WriteFile(path, []byte(b.String()), 0o600)
}

// unescapeDoubleQuoted resolves the only two escape sequences our
// renderer emits: `\"` -> `"` and `\\` -> `\`. We deliberately do
// not implement systemd's full grammar (no `\n`, `\t`, octal, ...)
// because we only ever round-trip values we wrote ourselves; users
// editing the file by hand should keep the syntax simple.
func unescapeDoubleQuoted(v string) string {
	var b strings.Builder
	b.Grow(len(v))
	for i := 0; i < len(v); i++ {
		if v[i] == '\\' && i+1 < len(v) {
			next := v[i+1]
			if next == '"' || next == '\\' {
				b.WriteByte(next)
				i++
				continue
			}
		}
		b.WriteByte(v[i])
	}
	return b.String()
}

func needsQuoting(v string) bool {
	if v == "" {
		return false
	}
	for _, r := range v {
		if r == ' ' || r == '\t' || r == '"' || r == '\'' || r == '#' || r == '\\' {
			return true
		}
	}
	return false
}
